language: java
jdk:
  - oraclejdk8
dist: trusty
env:
  - NODE_VERSION="8"
sudo: required
git:
  depth: false
addons:
  sonarcloud:
    organization: "orkunkocyigit-github"
before_install:
  - "wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip -d /tmp"
  - "unzip sonar-scanner-cli-3.3.0.1492-linux.zip -d /tmp"
  - "nvm install $NODE_VERSION"
  - "npm update -g npm"
  - "npm ci"
script:
  - npm test
  - /tmp/sonar-scanner-3.3.0.1492-linux/bin/sonar-scanner -Dsonar.login=$SONAR_TOKEN
  - npm run production-build
